"""v2.11-WP10 (Bucket C4) — sweep alembic migrations for ``None``-named
or missing constraint names.

Background
----------
v2.10-WP06 found ONE migration (``7f57993c9b09_add_domains_table_and_...``)
where the autogenerated stub left ``op.create_foreign_key(None, ...)``
and ``op.drop_constraint(None, ...)`` with literal ``None`` as the
constraint name. The downgrade was unrunnable
(``CompileError: Can't emit DROP CONSTRAINT for constraint ... it has no
name``). That migration was patched in-place; this test extends the
guard project-wide so the next auto-generated stub can't slip the same
defect into another file.

Scope
-----
Scans every ``alembic/versions/*.py`` for:

* ``op.create_foreign_key(None, ...)`` or ``op.create_foreign_key()``
  with the name arg missing/empty.
* ``op.drop_constraint(None, ...)`` with literal ``None`` as the name.

Both surfaces are AST-level: comments and docstrings are inherently
out of scope (they can't reach ``Call.args[0]``). The lint is paired
with a synthetic-bad self-test so future drift in the scanner itself
is caught.

Relationship to ``test_domains_fkey_downgrade.py``
--------------------------------------------------
That file targets the one fixed migration explicitly. This file is the
project-wide sweep — it would have caught the WP06 bug across any
migration, not just the known one.
"""
from __future__ import annotations

import ast
import pathlib

import pytest

from tests.helpers.source_lint import iter_source_files, parse_module


_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
_VERSIONS_DIR = _REPO_ROOT / "alembic" / "versions"


# Functions where the FIRST positional argument is the constraint name.
# alembic signatures:
#   op.create_foreign_key(constraint_name, source, referent, local_cols, remote_cols, ...)
#   op.drop_constraint(constraint_name, table_name, type_=...)
#   op.create_unique_constraint(constraint_name, table_name, columns, ...)
#   op.create_check_constraint(constraint_name, table_name, condition, ...)
#   op.create_primary_key(constraint_name, table_name, columns, ...)
_NAME_FIRST_ARG_FUNCS = {
    "create_foreign_key",
    "create_unique_constraint",
    "create_check_constraint",
    "create_primary_key",
    "drop_constraint",
}


def _iter_version_files() -> list[pathlib.Path]:
    # versions/ is flat in this repo; rglob via the helper degenerates to
    # glob. Exclude __init__.py the way the original lint did.
    return [
        p for p in iter_source_files(_VERSIONS_DIR)
        if p.name != "__init__.py"
    ]


def _is_target_call(node: ast.Call) -> str | None:
    """Return the matched function name if ``node`` is one of the
    constraint-creating alembic calls; otherwise ``None``.

    Matches both ``op.create_foreign_key(...)`` (Attribute) and a bare
    ``create_foreign_key(...)`` (Name) — some migrations rebind the
    function locally.
    """
    func = node.func
    if isinstance(func, ast.Attribute) and func.attr in _NAME_FIRST_ARG_FUNCS:
        return func.attr
    if isinstance(func, ast.Name) and func.id in _NAME_FIRST_ARG_FUNCS:
        return func.id
    return None


def _scan(path: pathlib.Path) -> list[tuple[int, str, str]]:
    """Return ``[(lineno, func_name, reason), ...]`` for each hit in
    ``path``. A hit means the first positional argument is ``None``
    (``ast.Constant(value=None)``) or the call has zero positional args
    (name was passed as a keyword — also acceptable to skip, but rare
    enough that we flag it for review).
    """
    hits: list[tuple[int, str, str]] = []
    tree = parse_module(path)
    if tree is None:
        # Skip files that aren't valid Python — alembic occasionally
        # ships scratch files in non-version dirs but this folder is
        # python-only by convention.
        return hits

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        matched = _is_target_call(node)
        if matched is None:
            continue
        # Look at the first positional arg only — keyword-passed name
        # (``name=...``) is not idiomatic alembic and would also be
        # suspicious, but we don't flag it here to keep the lint tight.
        if not node.args:
            hits.append((node.lineno, matched, "missing positional name arg"))
            continue
        first = node.args[0]
        if isinstance(first, ast.Constant) and first.value is None:
            hits.append((node.lineno, matched, "first positional arg is None"))
    return hits


def test_no_none_named_constraint_in_alembic_versions():
    """No ``op.create_foreign_key(None, ...)`` / ``op.drop_constraint(
    None, ...)`` (or peers) in any alembic version file.

    A ``None`` name lets postgres pick its default
    (``<table>_<col>_fkey``) on upgrade but renders the matching
    downgrade unrunnable — alembic can't emit ``DROP CONSTRAINT`` on
    an unnamed ``ForeignKeyConstraint`` and raises ``CompileError``.

    v2.10-WP06 fixed the one historical hit (``7f57993c9b09``); WP10
    extends the static guard project-wide so the next auto-stub gets
    caught before merge. The companion ``naming_convention`` on
    ``Base.metadata`` is what stops future auto-generators from
    emitting ``None`` in the first place.
    """
    all_hits: list[tuple[pathlib.Path, int, str, str]] = []
    for path in _iter_version_files():
        for lineno, func, reason in _scan(path):
            all_hits.append((path, lineno, func, reason))

    if all_hits:
        lines = [
            f"  {p.relative_to(_REPO_ROOT)}:{lineno}: op.{func}(...) — {reason}"
            for p, lineno, func, reason in all_hits
        ]
        pytest.fail(
            "Alembic migration(s) declare constraints with a missing or "
            "``None`` name — postgres will auto-name them, but the matching "
            "drop_constraint cannot run. Give the constraint an explicit "
            "name (see ``Base.metadata.naming_convention`` for the project "
            "convention):\n" + "\n".join(lines)
        )


def test_alembic_constraint_name_lint_detects_synthetic_bad(tmp_path: pathlib.Path):
    """Self-test: the scanner flags both ``None``-name forms it targets,
    and does NOT flag a correctly-named call.

    Cases:

    1. ``op.create_foreign_key(None, ...)`` — must flag.
    2. ``op.drop_constraint(None, ...)`` — must flag.
    3. ``op.create_unique_constraint(None, ...)`` — must flag (same family).
    4. ``op.create_foreign_key("fk_a_b", ...)`` — must NOT flag.
    5. Bare ``create_foreign_key(None, ...)`` (no ``op.`` prefix) — must flag.
    """
    bad_fk = tmp_path / "bad_fk.py"
    bad_fk.write_text(
        "from alembic import op\n"
        "def upgrade():\n"
        "    op.create_foreign_key(None, 't1', 't2', ['c'], ['id'])\n"
    )
    assert _scan(bad_fk), "scanner should flag op.create_foreign_key(None, ...)"

    bad_drop = tmp_path / "bad_drop.py"
    bad_drop.write_text(
        "from alembic import op\n"
        "def downgrade():\n"
        "    op.drop_constraint(None, 't1', type_='foreignkey')\n"
    )
    assert _scan(bad_drop), "scanner should flag op.drop_constraint(None, ...)"

    bad_uq = tmp_path / "bad_uq.py"
    bad_uq.write_text(
        "from alembic import op\n"
        "def upgrade():\n"
        "    op.create_unique_constraint(None, 't1', ['c'])\n"
    )
    assert _scan(bad_uq), (
        "scanner should flag op.create_unique_constraint(None, ...)"
    )

    good = tmp_path / "good.py"
    good.write_text(
        "from alembic import op\n"
        "def upgrade():\n"
        "    op.create_foreign_key('fk_t1_c_t2', 't1', 't2', ['c'], ['id'])\n"
        "def downgrade():\n"
        "    op.drop_constraint('fk_t1_c_t2', 't1', type_='foreignkey')\n"
    )
    assert not _scan(good), (
        "scanner must not flag a correctly-named create/drop pair"
    )

    bare = tmp_path / "bare.py"
    bare.write_text(
        "from alembic.op import create_foreign_key\n"
        "def upgrade():\n"
        "    create_foreign_key(None, 't1', 't2', ['c'], ['id'])\n"
    )
    assert _scan(bare), (
        "scanner should flag a bare ``create_foreign_key(None, ...)`` "
        "call (no ``op.`` prefix)"
    )
