"""add domains table and domain_id to problems

Revision ID: 7f57993c9b09
Revises: ec940c7db8f3
Create Date: 2026-04-15 15:35:47.388993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f57993c9b09'
down_revision: Union[str, None] = 'ec940c7db8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('problems', sa.Column('domain_id', sa.UUID(), nullable=True))
    # WP06: name the FK explicitly so the downgrade can drop it by name.
    # The auto-generated stub passed None on both sides, which made
    # downgrade unrunnable (alembic CompileError: can't emit DROP
    # CONSTRAINT without a name). Use a batch-fix so existing databases
    # whose FK was auto-named by postgres (problems_domain_id_fkey) are
    # rewritten to the stable name before downgrade.
    op.execute(
        "ALTER TABLE problems "
        "DROP CONSTRAINT IF EXISTS problems_domain_id_fkey"
    )
    op.create_foreign_key(
        'fk_problems_domain_id_domains',
        'problems', 'domains', ['domain_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WP06: drop both the WP06-named FK and the legacy auto-named one so
    # downgrade works on databases that were upgraded before the rename.
    op.execute(
        "ALTER TABLE problems "
        "DROP CONSTRAINT IF EXISTS fk_problems_domain_id_domains"
    )
    op.execute(
        "ALTER TABLE problems "
        "DROP CONSTRAINT IF EXISTS problems_domain_id_fkey"
    )
    op.drop_column('problems', 'domain_id')
    op.drop_table('domains')
    # ### end Alembic commands ###
