"""add seq_number to problems

Revision ID: ec940c7db8f3
Revises: a44727b02982
Create Date: 2026-04-15 15:28:11.229329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec940c7db8f3'
down_revision: Union[str, None] = 'a44727b02982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('seq_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_problems_seq_number'), 'problems', ['seq_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_seq_number'), table_name='problems')
    op.drop_column('problems', 'seq_number')
    # ### end Alembic commands ###
